### ISSUE TITLE
not support openresty 1.15.8.1

### ISSUE THREAD

**Issue by shuangxili** [openresty/openresty-gdb-utils#23]
when I use openresty 1.15.8.1
(gdb) lvmst
Traceback (most recent call last):
  File "/home/icache/hcs/hcs.nginx/bin/openresty-gdb-utils/luajit21.py", line 613, in invoke
    L = get_cur_L()
  File "/home/icache/hcs/hcs.nginx/bin/openresty-gdb-utils/luajit21.py", line 131, in get_cur_L
    return gcref(G(mL)['cur_L'])['th'].address
  File "/home/icache/hcs/hcs.nginx/bin/openresty-gdb-utils/luajit21.py", line 326, in G
    return mref(L['glref'], "global_State")
  File "/home/icache/hcs/hcs.nginx/bin/openresty-gdb-utils/luajit21.py", line 183, in mref
    return r['ptr32'].cast(typ("uintptr_t")).cast(typ(t + "*"))
gdb.error: There is no member named ptr32.
Error occurred in Python command: There is no member named ptr32.

**Comment by agentzh** [comment]
We're gonna provide all new tools through our OpenResty Trace platform. The existing open source tools are painful to maintain and extend for us.

**Comment by wutchzone** [comment]
Are there any news on the new tools? @agentzh

**Comment by agentzh** [comment]
This repo is superseded by the new OpenResty XRay platform:

https://openresty.com/en/xray

This repo uses hand-crafted python code which is too painful to maintain and enhance.
